[build]
builder = "nixpacks"

[start]
cmd = "node server.js"

[variables]
DATABASE_URL = "postgresql://postgres:iCvnJqAHHQnsafVjMHowoMnXUxrUZEyg@postgres.railway.internal:5432/railway"
HDS_API_URL = "https://api.homedelivery.com.au"
HDS_EMAIL = "tomi@workoutmeals.com.au"
HDS_PASSWORD = "Zadomspremni01!"
TZ = "Australia/Sydney"
