-- Insert all 28 regions into the database
INSERT INTO regions (id, name, hds_zone, enabled, created_at, updated_at) VALUES
(1, 'NSW Sydney Metro', 'NSW Sydney Metro', true, NOW(), NOW()),
(2, 'NSW Newcastle', 'NSW Newcastle', true, NOW(), NOW()),
(3, 'NSW Wollongong Coast', 'NSW Wollongong Coast', true, NOW(), NOW()),
(4, 'NSW Coffs Harbour', 'NSW Coffs Harbour', true, NOW(), NOW()),
(5, 'NSW Armidale', 'NSW Armidale', true, NOW(), NOW()),
(6, 'NSW Tamworth', 'NSW Tamworth', true, NOW(), NOW()),
(7, 'VIC Melbourne Metro', 'VIC Melbourne Metro', true, NOW(), NOW()),
(8, 'VIC Geelong', 'VIC Geelong', true, NOW(), NOW()),
(9, 'VIC Ballarat', 'VIC Ballarat', true, NOW(), NOW()),
(10, 'VIC Bendigo', 'VIC Bendigo', true, NOW(), NOW()),
(11, 'VIC Shepparton', 'VIC Shepparton', true, NOW(), NOW()),
(12, 'VIC Regional West - Warrnambool', 'VIC Regional West - Warrnambool', true, NOW(), NOW()),
(13, 'VIC Albury Wodonga', 'VIC Albury Wodonga', true, NOW(), NOW()),
(14, 'QLD Brisbane Metro', 'QLD Brisbane Metro', true, NOW(), NOW()),
(15, 'QLD Toowoomba', 'QLD Toowoomba', true, NOW(), NOW()),
(16, 'QLD Lismore', 'QLD Lismore', true, NOW(), NOW()),
(17, 'QLD-FNQ Cairns', 'QLD-FNQ Cairns', true, NOW(), NOW()),
(18, 'QLD-FNQ Townsville', 'QLD-FNQ Townsville', true, NOW(), NOW()),
(19, 'QLD-FNQ Rockhampton', 'QLD-FNQ Rockhampton', true, NOW(), NOW()),
(20, 'QLD-FNQ Mackay', 'QLD-FNQ Mackay', true, NOW(), NOW()),
(21, 'WA Perth Metro', 'WA Perth Metro', true, NOW(), NOW()),
(22, 'WA South Coast - Bunbury 2 - Busselton', 'WA South Coast - Bunbury 2 - Busselton', true, NOW(), NOW()),
(23, 'WA Fremantle', 'WA Fremantle', true, NOW(), NOW()),
(24, 'SA Adelaide Metro', 'SA Adelaide Metro', true, NOW(), NOW()),
(25, 'ACT Canberra Metro', 'ACT Canberra Metro', true, NOW(), NOW()),
(26, 'TAS Hobart Metro', 'TAS Hobart Metro', true, NOW(), NOW()),
(27, 'TAS Launceston Metro', 'TAS Launceston Metro', true, NOW(), NOW()),
(28, 'NT Darwin Metro', 'NT Darwin Metro', true, NOW(), NOW())
ON CONFLICT (id) DO UPDATE SET 
  name = EXCLUDED.name,
  hds_zone = EXCLUDED.hds_zone,
  updated_at = NOW();
