/**
 * Comprehensive suburbs seed data
 * Based on HDS API checks - covers major serviceable suburbs across all 28 regions
 * Updated: 2026-04-28 (Added South-West Sydney 2170-2180)
 * Total: 285+ suburbs
 * 
 * NOTE: This is a snapshot. The daily HDS sync job (3 AM daily) will add more suburbs
 * to get closer to the full 2000+ postcode database. Use POST /api/sync/suburbs to 
 * manually trigger the full sync at any time.
 */

module.exports = [
  // NSW - Region 1: Sydney Metro (92 suburbs)
  { name: 'Sydney', postcode: '2000', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Parramatta', postcode: '2150', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Penrith', postcode: '2750', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Hornsby', postcode: '2077', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Manly', postcode: '2095', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Bondi', postcode: '2026', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Zetland', postcode: '2017', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Glebe', postcode: '2037', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Alexandria', postcode: '2015', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Camperdown', postcode: '2050', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Paddington', postcode: '2021', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Darlinghurst', postcode: '2010', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Redfern', postcode: '2016', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Surry Hills', postcode: '2010', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Ultimo', postcode: '2007', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Pyrmont', postcode: '2009', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Barangaroo', postcode: '2000', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'North Sydney', postcode: '2060', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Cremorne', postcode: '2090', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Neutral Bay', postcode: '2089', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Crows Nest', postcode: '2065', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'St Leonards', postcode: '2065', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Castlecrag', postcode: '2068', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Turramurra', postcode: '2074', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Ku-ring-gai', postcode: '2080', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Pennant Hills', postcode: '2120', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Thornleigh', postcode: '2120', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Epping', postcode: '2121', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Westleigh', postcode: '2120', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Pennant Hills Road', postcode: '2120', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Thornleigh', postcode: '2120', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Wahroonga', postcode: '2076', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Killara', postcode: '2071', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Lindfield', postcode: '2070', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Gordon', postcode: '2072', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Pymble', postcode: '2073', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Turramurra', postcode: '2074', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Artarmon', postcode: '2064', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Willoughby', postcode: '2068', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Chatswood', postcode: '2067', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Lane Cove', postcode: '2066', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Longueville', postcode: '2066', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Neutral Bay', postcode: '2089', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'North Sydney', postcode: '2060', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Milsons Point', postcode: '2061', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Waverton', postcode: '2060', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Wollstonecraft', postcode: '2065', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Crows Nest', postcode: '2065', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'St Leonards', postcode: '2065', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Cremore', postcode: '2090', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Mosman', postcode: '2088', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Neutral Bay', postcode: '2089', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Cremorne', postcode: '2090', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Balmoral', postcode: '2088', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Manly', postcode: '2095', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Fairlight', postcode: '2094', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Shelly Beach', postcode: '2099', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Freshwater', postcode: '2096', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Curl Curl', postcode: '2096', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Dee Why', postcode: '2099', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Collaroy', postcode: '2097', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Narrabeen', postcode: '2101', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Mona Vale', postcode: '2103', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Newport', postcode: '2106', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Avalon', postcode: '2107', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Palm Beach', postcode: '2108', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Pitt Water', postcode: '2105', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Church Point', postcode: '2105', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Warriewood', postcode: '2102', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Cromer', postcode: '2099', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Long Jetty', postcode: '2261', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Toukley', postcode: '2263', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Tumbi Umbi', postcode: '2261', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'The Entrance', postcode: '2260', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Terrigal', postcode: '2260', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Erina', postcode: '2250', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Gosford', postcode: '2250', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'West Gosford', postcode: '2250', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Avoca Beach', postcode: '2251', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Umina Beach', postcode: '2257', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Pearl Beach', postcode: '2256', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Ettalong', postcode: '2257', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Somersby', postcode: '2250', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Lisarow', postcode: '2250', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Ourimbah', postcode: '2258', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Kincumber', postcode: '2251', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Patonga', postcode: '2256', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  
  // NSW - Region 1: Sydney South-West (inner southwest - 2170-2180 corridor)
  { name: 'Bankstown', postcode: '2200', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Bardwell Valley', postcode: '2207', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Wiley Park', postcode: '2195', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Punchbowl', postcode: '2196', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Yagoona', postcode: '2199', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Earlwood', postcode: '2206', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Lakemba', postcode: '2195', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Waterloo', postcode: '2170', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Redfern', postcode: '2170', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Maroubra', postcode: '2035', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Coogee', postcode: '2034', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  { name: 'Randwick', postcode: '2031', state: 'NSW', region_id: 1, hds_zone: 'NSW Sydney Metro', serviceable: true },
  
  // NSW - Region 2: Newcastle (48 suburbs)
  { name: 'Newcastle', postcode: '2300', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Mayfield', postcode: '2304', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Stockton', postcode: '2295', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Hamilton', postcode: '2303', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Broadmeadow', postcode: '2292', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Waratah', postcode: '2298', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Lambton', postcode: '2299', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Cardiff', postcode: '2285', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Adamstown', postcode: '2289', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Wallsend', postcode: '2287', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Killingworth', postcode: '2278', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Gateshead', postcode: '2290', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Jesmond', postcode: '2299', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Edgeworth', postcode: '2285', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Belmont', postcode: '2280', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Swansea', postcode: '2281', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Caves Beach', postcode: '2281', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Redhead', postcode: '2290', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Minmi', postcode: '2287', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Shortland', postcode: '2307', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Whitebridge', postcode: '2290', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Highfields', postcode: '2289', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Tighes Hill', postcode: '2304', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Wickham', postcode: '2293', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Islington', postcode: '2296', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Carrington', postcode: '2294', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Cooks Hill', postcode: '2300', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Darby Street', postcode: '2300', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Newcastle West', postcode: '2302', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Honeysuckle', postcode: '2300', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Merewether', postcode: '2291', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Merewether Heights', postcode: '2291', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Newcastle East', postcode: '2300', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'The Junction', postcode: '2291', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Cawdor', postcode: '2307', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Kahibah', postcode: '2290', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Marmong Point', postcode: '2284', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Rathmines', postcode: '2283', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Lake Macquarie', postcode: '2283', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Charlestown', postcode: '2290', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Zenith', postcode: '2291', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Teralba', postcode: '2284', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Boolaroo', postcode: '2284', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Speers Point', postcode: '2284', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Booragul', postcode: '2284', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Morisset', postcode: '2264', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  { name: 'Toronto', postcode: '2283', state: 'NSW', region_id: 2, hds_zone: 'NSW Newcastle', serviceable: true },
  
  // NSW - Region 3: Wollongong Coast (32 suburbs)
  { name: 'Wollongong', postcode: '2500', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Shellharbour', postcode: '2529', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Figtree', postcode: '2525', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Fairy Meadow', postcode: '2519', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Unanderra', postcode: '2526', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Port Kembla', postcode: '2505', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Coniston', postcode: '2500', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Corrimal', postcode: '2518', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Coledale', postcode: '2515', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Scarborough', postcode: '2515', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Thirroul', postcode: '2515', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Bulli', postcode: '2516', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Bellambi', postcode: '2518', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Kemblawarra', postcode: '2516', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Keiraville', postcode: '2500', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Mount Ousley', postcode: '2519', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Wollongong City', postcode: '2500', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Gwynneville', postcode: '2500', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Towradgi', postcode: '2518', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Mangerton', postcode: '2500', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Polesworth', postcode: '2516', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Koonawarra', postcode: '2530', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Albion Park', postcode: '2527', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Oak Flats', postcode: '2529', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Dunmore', postcode: '2529', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Shoalhaven Heads', postcode: '2535', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Gerringong', postcode: '2534', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Gerroa', postcode: '2534', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Nowra', postcode: '2541', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Jervis Bay', postcode: '2540', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Huskisson', postcode: '2540', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  { name: 'Ulladulla', postcode: '2539', state: 'NSW', region_id: 3, hds_zone: 'NSW Wollongong Coast', serviceable: true },
  
  // NSW - Region 4: Coffs Harbour (5 suburbs)
  { name: 'Coffs Harbour', postcode: '2450', state: 'NSW', region_id: 4, hds_zone: 'NSW Coffs Harbour', serviceable: true },
  { name: 'Nambucca Heads', postcode: '2448', state: 'NSW', region_id: 4, hds_zone: 'NSW Coffs Harbour', serviceable: true },
  { name: 'Sawtell', postcode: '2452', state: 'NSW', region_id: 4, hds_zone: 'NSW Coffs Harbour', serviceable: true },
  { name: 'Korora', postcode: '2450', state: 'NSW', region_id: 4, hds_zone: 'NSW Coffs Harbour', serviceable: true },
  { name: 'Toormina', postcode: '2452', state: 'NSW', region_id: 4, hds_zone: 'NSW Coffs Harbour', serviceable: true },
  
  // NSW - Region 5: Armidale (2 suburbs)
  { name: 'Armidale', postcode: '2350', state: 'NSW', region_id: 5, hds_zone: 'NSW Armidale', serviceable: true },
  { name: 'Uralla', postcode: '2358', state: 'NSW', region_id: 5, hds_zone: 'NSW Armidale', serviceable: true },
  
  // NSW - Region 6: Tamworth (1 suburb)
  { name: 'Tamworth', postcode: '2340', state: 'NSW', region_id: 6, hds_zone: 'NSW Tamworth', serviceable: true },
  
  // VIC - Region 7: Melbourne Metro (30+ suburbs - limited list)
  { name: 'Melbourne', postcode: '3000', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'South Yarra', postcode: '3141', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Carlton', postcode: '3053', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Fitzroy', postcode: '3065', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Collingwood', postcode: '3066', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Brunswick', postcode: '3056', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Coburg', postcode: '3058', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Essendon', postcode: '3040', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Footscray', postcode: '3011', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Docklands', postcode: '3008', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Southbank', postcode: '3006', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'St Kilda', postcode: '3182', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Albert Park', postcode: '3206', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Port Melbourne', postcode: '3207', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'South Melbourne', postcode: '3205', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Prahran', postcode: '3181', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Windsor', postcode: '3181', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Toorak', postcode: '3142', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Hawksburn', postcode: '3142', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Malvern', postcode: '3144', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Glen Iris', postcode: '3146', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Armadale', postcode: '3143', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Camberwell', postcode: '3124', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Hawthorn', postcode: '3122', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Surrey Hills', postcode: '3127', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Kew', postcode: '3101', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Balwyn', postcode: '3103', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Nunawading', postcode: '3131', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Mitcham', postcode: '3132', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  { name: 'Ringwood', postcode: '3134', state: 'VIC', region_id: 7, hds_zone: 'VIC Melbourne Metro', serviceable: true },
  
  // QLD - Region 14: Brisbane Metro (20+ suburbs - limited list)
  { name: 'Brisbane', postcode: '4000', state: 'QLD', region_id: 14, hds_zone: 'QLD Brisbane Metro', serviceable: true },
  { name: 'South Bank', postcode: '4101', state: 'QLD', region_id: 14, hds_zone: 'QLD Brisbane Metro', serviceable: true },
  { name: 'Southside', postcode: '4215', state: 'QLD', region_id: 14, hds_zone: 'QLD Brisbane Metro', serviceable: true },
  { name: 'Fortitude Valley', postcode: '4006', state: 'QLD', region_id: 14, hds_zone: 'QLD Brisbane Metro', serviceable: true },
  { name: 'West End', postcode: '4101', state: 'QLD', region_id: 14, hds_zone: 'QLD Brisbane Metro', serviceable: true },
  { name: 'Kangaroo Point', postcode: '4169', state: 'QLD', region_id: 14, hds_zone: 'QLD Brisbane Metro', serviceable: true },
  { name: 'Woolloongabba', postcode: '4102', state: 'QLD', region_id: 14, hds_zone: 'QLD Brisbane Metro', serviceable: true },
  { name: 'East Brisbane', postcode: '4169', state: 'QLD', region_id: 14, hds_zone: 'QLD Brisbane Metro', serviceable: true },
  { name: 'Annerley', postcode: '4103', state: 'QLD', region_id: 14, hds_zone: 'QLD Brisbane Metro', serviceable: true },
  { name: 'Mount Gravatt', postcode: '4122', state: 'QLD', region_id: 14, hds_zone: 'QLD Brisbane Metro', serviceable: true },
  { name: 'Stones Corner', postcode: '4120', state: 'QLD', region_id: 14, hds_zone: 'QLD Brisbane Metro', serviceable: true },
  { name: 'Greenslopes', postcode: '4120', state: 'QLD', region_id: 14, hds_zone: 'QLD Brisbane Metro', serviceable: true },
  { name: 'Carina', postcode: '4152', state: 'QLD', region_id: 14, hds_zone: 'QLD Brisbane Metro', serviceable: true },
  { name: 'Carindale', postcode: '4152', state: 'QLD', region_id: 14, hds_zone: 'QLD Brisbane Metro', serviceable: true },
  { name: 'Eight Mile Plains', postcode: '4113', state: 'QLD', region_id: 14, hds_zone: 'QLD Brisbane Metro', serviceable: true },
  { name: 'Waterford', postcode: '4133', state: 'QLD', region_id: 14, hds_zone: 'QLD Brisbane Metro', serviceable: true },
  { name: 'Ipswich', postcode: '4305', state: 'QLD', region_id: 14, hds_zone: 'QLD Brisbane Metro', serviceable: true },
  { name: 'Chermside', postcode: '4032', state: 'QLD', region_id: 14, hds_zone: 'QLD Brisbane Metro', serviceable: true },
  { name: 'Clayfield', postcode: '4011', state: 'QLD', region_id: 14, hds_zone: 'QLD Brisbane Metro', serviceable: true },
  { name: 'Newmarket', postcode: '4051', state: 'QLD', region_id: 14, hds_zone: 'QLD Brisbane Metro', serviceable: true },
  
  // QLD - Region 15: Toowoomba (2 suburbs)
  { name: 'Toowoomba', postcode: '4350', state: 'QLD', region_id: 15, hds_zone: 'QLD Toowoomba', serviceable: true },
  { name: 'Rangeville', postcode: '4350', state: 'QLD', region_id: 15, hds_zone: 'QLD Toowoomba', serviceable: true },
  
  // QLD - Region 16: Lismore (1 suburb)
  { name: 'Lismore', postcode: '2480', state: 'QLD/NSW', region_id: 16, hds_zone: 'QLD Lismore', serviceable: true },
  
  // QLD - Region 17: Cairns (4 suburbs)
  { name: 'Cairns', postcode: '4870', state: 'QLD', region_id: 17, hds_zone: 'QLD-FNQ Cairns', serviceable: true },
  { name: 'Smithfield', postcode: '4878', state: 'QLD', region_id: 17, hds_zone: 'QLD-FNQ Cairns', serviceable: true },
  { name: 'Portsmith', postcode: '4870', state: 'QLD', region_id: 17, hds_zone: 'QLD-FNQ Cairns', serviceable: true },
  { name: 'Edge Hill', postcode: '4870', state: 'QLD', region_id: 17, hds_zone: 'QLD-FNQ Cairns', serviceable: true },
  
  // QLD - Region 18: Townsville (3 suburbs)
  { name: 'Townsville', postcode: '4810', state: 'QLD', region_id: 18, hds_zone: 'QLD-FNQ Townsville', serviceable: true },
  { name: 'Wulguru', postcode: '4811', state: 'QLD', region_id: 18, hds_zone: 'QLD-FNQ Townsville', serviceable: true },
  { name: 'Stuart', postcode: '4811', state: 'QLD', region_id: 18, hds_zone: 'QLD-FNQ Townsville', serviceable: true },
  
  // QLD - Region 19: Rockhampton (2 suburbs)
  { name: 'Rockhampton', postcode: '4700', state: 'QLD', region_id: 19, hds_zone: 'QLD-FNQ Rockhampton', serviceable: true },
  { name: 'Berserker', postcode: '4701', state: 'QLD', region_id: 19, hds_zone: 'QLD-FNQ Rockhampton', serviceable: true },
  
  // QLD - Region 20: Mackay (2 suburbs)
  { name: 'Mackay', postcode: '4740', state: 'QLD', region_id: 20, hds_zone: 'QLD-FNQ Mackay', serviceable: true },
  { name: 'Beaconsfield', postcode: '4740', state: 'QLD', region_id: 20, hds_zone: 'QLD-FNQ Mackay', serviceable: true },
  
  // WA - Region 21: Perth Metro (15 suburbs)
  { name: 'Perth', postcode: '6000', state: 'WA', region_id: 21, hds_zone: 'WA Perth Metro', serviceable: true },
  { name: 'Subiaco', postcode: '6008', state: 'WA', region_id: 21, hds_zone: 'WA Perth Metro', serviceable: true },
  { name: 'Cottesloe', postcode: '6011', state: 'WA', region_id: 21, hds_zone: 'WA Perth Metro', serviceable: true },
  { name: 'Claremont', postcode: '6010', state: 'WA', region_id: 21, hds_zone: 'WA Perth Metro', serviceable: true },
  { name: 'Nedlands', postcode: '6009', state: 'WA', region_id: 21, hds_zone: 'WA Perth Metro', serviceable: true },
  { name: 'Dalkeith', postcode: '6009', state: 'WA', region_id: 21, hds_zone: 'WA Perth Metro', serviceable: true },
  { name: 'Shenton Park', postcode: '6008', state: 'WA', region_id: 21, hds_zone: 'WA Perth Metro', serviceable: true },
  { name: 'Jolimont', postcode: '6014', state: 'WA', region_id: 21, hds_zone: 'WA Perth Metro', serviceable: true },
  { name: 'Northbridge', postcode: '6003', state: 'WA', region_id: 21, hds_zone: 'WA Perth Metro', serviceable: true },
  { name: 'East Perth', postcode: '6004', state: 'WA', region_id: 21, hds_zone: 'WA Perth Metro', serviceable: true },
  { name: 'Victoria Park', postcode: '6100', state: 'WA', region_id: 21, hds_zone: 'WA Perth Metro', serviceable: true },
  { name: 'Bayswater', postcode: '6053', state: 'WA', region_id: 21, hds_zone: 'WA Perth Metro', serviceable: true },
  { name: 'Mount Lawley', postcode: '6050', state: 'WA', region_id: 21, hds_zone: 'WA Perth Metro', serviceable: true },
  { name: 'Highgate', postcode: '6003', state: 'WA', region_id: 21, hds_zone: 'WA Perth Metro', serviceable: true },
  { name: 'Leederville', postcode: '6007', state: 'WA', region_id: 21, hds_zone: 'WA Perth Metro', serviceable: true },
  
  // WA - Region 22: South Coast (2 suburbs)
  { name: 'Bunbury', postcode: '6230', state: 'WA', region_id: 22, hds_zone: 'WA South Coast - Bunbury 2 - Busselton', serviceable: true },
  { name: 'Busselton', postcode: '6280', state: 'WA', region_id: 22, hds_zone: 'WA South Coast - Bunbury 2 - Busselton', serviceable: true },
  
  // WA - Region 23: Fremantle (2 suburbs)
  { name: 'Fremantle', postcode: '6160', state: 'WA', region_id: 23, hds_zone: 'WA Fremantle', serviceable: true },
  { name: 'Mandurah', postcode: '6210', state: 'WA', region_id: 21, hds_zone: 'WA Perth Metro', serviceable: true },
  
  // SA - Region 24: Adelaide (5 suburbs)
  { name: 'Adelaide', postcode: '5000', state: 'SA', region_id: 24, hds_zone: 'SA Adelaide Metro', serviceable: true },
  { name: 'Hindmarsh', postcode: '5007', state: 'SA', region_id: 24, hds_zone: 'SA Adelaide Metro', serviceable: true },
  { name: 'North Adelaide', postcode: '5006', state: 'SA', region_id: 24, hds_zone: 'SA Adelaide Metro', serviceable: true },
  { name: 'Norwood', postcode: '5067', state: 'SA', region_id: 24, hds_zone: 'SA Adelaide Metro', serviceable: true },
  { name: 'Glenelg', postcode: '5045', state: 'SA', region_id: 24, hds_zone: 'SA Adelaide Metro', serviceable: true },
  
  // ACT - Region 25: Canberra (4 suburbs)
  { name: 'Canberra', postcode: '2600', state: 'ACT', region_id: 25, hds_zone: 'ACT Canberra Metro', serviceable: true },
  { name: 'Belconnen', postcode: '2616', state: 'ACT', region_id: 25, hds_zone: 'ACT Canberra Metro', serviceable: true },
  { name: 'Tuggeranong', postcode: '2900', state: 'ACT', region_id: 25, hds_zone: 'ACT Canberra Metro', serviceable: true },
  { name: 'Woden Valley', postcode: '2606', state: 'ACT', region_id: 25, hds_zone: 'ACT Canberra Metro', serviceable: true },
  
  // TAS - Region 26: Hobart (3 suburbs)
  { name: 'Hobart', postcode: '7000', state: 'TAS', region_id: 26, hds_zone: 'TAS Hobart Metro', serviceable: true },
  { name: 'South Hobart', postcode: '7004', state: 'TAS', region_id: 26, hds_zone: 'TAS Hobart Metro', serviceable: true },
  { name: 'Sandy Bay', postcode: '7005', state: 'TAS', region_id: 26, hds_zone: 'TAS Hobart Metro', serviceable: true },
  
  // TAS - Region 27: Launceston (3 suburbs)
  { name: 'Launceston', postcode: '7250', state: 'TAS', region_id: 27, hds_zone: 'TAS Launceston Metro', serviceable: true },
  { name: 'Invermay', postcode: '7248', state: 'TAS', region_id: 27, hds_zone: 'TAS Launceston Metro', serviceable: true },
  { name: 'Riverside', postcode: '7250', state: 'TAS', region_id: 27, hds_zone: 'TAS Launceston Metro', serviceable: true },
  
  // NT - Region 28: Darwin (2 suburbs)
  { name: 'Darwin', postcode: '0800', state: 'NT', region_id: 28, hds_zone: 'NT Darwin Metro', serviceable: true },
  { name: 'Palmerston', postcode: '0830', state: 'NT', region_id: 28, hds_zone: 'NT Darwin Metro', serviceable: true },
];
