// Comprehensive Sydney and Melbourne suburbs with postcodes
// Used for production-grade postcode lookup

const sydneySuburbs = [
  { postcode: '2000', suburb: 'Sydney', state: 'NSW', region_id: 1 },
  { postcode: '2150', suburb: 'Parramatta', state: 'NSW', region_id: 1 },
  { postcode: '2095', suburb: 'Manly', state: 'NSW', region_id: 1 },
  { postcode: '2026', suburb: 'Bondi', state: 'NSW', region_id: 1 },
  { postcode: '2034', suburb: 'Coogee', state: 'NSW', region_id: 1 },
  { postcode: '2031', suburb: 'Randwick', state: 'NSW', region_id: 1 },
  { postcode: '2021', suburb: 'Paddington', state: 'NSW', region_id: 1 },
  { postcode: '2010', suburb: 'Surry Hills', state: 'NSW', region_id: 1 },
  { postcode: '2042', suburb: 'Newtown', state: 'NSW', region_id: 1 },
  { postcode: '2067', suburb: 'Chatswood', state: 'NSW', region_id: 1 },
  { postcode: '2121', suburb: 'Epping', state: 'NSW', region_id: 1 },
  { postcode: '2120', suburb: 'Pennant Hills', state: 'NSW', region_id: 1 },
  { postcode: '2077', suburb: 'Hornsby', state: 'NSW', region_id: 1 },
  { postcode: '2073', suburb: 'Pymble', state: 'NSW', region_id: 1 },
  { postcode: '2074', suburb: 'Turramurra', state: 'NSW', region_id: 1 },
  { postcode: '2070', suburb: 'Lindfield', state: 'NSW', region_id: 1 },
  { postcode: '2072', suburb: 'Gordon', state: 'NSW', region_id: 1 },
  { postcode: '2068', suburb: 'Willoughby', state: 'NSW', region_id: 1 },
  { postcode: '2075', suburb: 'St Ives', state: 'NSW', region_id: 1 },
  { postcode: '2069', suburb: 'Roseville', state: 'NSW', region_id: 1 },
  { postcode: '2089', suburb: 'Neutral Bay', state: 'NSW', region_id: 1 },
  { postcode: '2090', suburb: 'Cremorne', state: 'NSW', region_id: 1 },
  { postcode: '2066', suburb: 'Lane Cove', state: 'NSW', region_id: 1 },
  { postcode: '2060', suburb: 'North Sydney', state: 'NSW', region_id: 1 },
  { postcode: '2088', suburb: 'Mosman', state: 'NSW', region_id: 1 },
  { postcode: '2065', suburb: 'Crows Nest', state: 'NSW', region_id: 1 },
  { postcode: '2064', suburb: 'Artarmon', state: 'NSW', region_id: 1 },
  { postcode: '2062', suburb: 'Cammeray', state: 'NSW', region_id: 1 },
  { postcode: '2061', suburb: 'Milsons Point', state: 'NSW', region_id: 1 },
  { postcode: '2028', suburb: 'Double Bay', state: 'NSW', region_id: 1 },
  { postcode: '2029', suburb: 'Rose Bay', state: 'NSW', region_id: 1 },
  { postcode: '2030', suburb: 'Vaucluse', state: 'NSW', region_id: 1 },
  { postcode: '2023', suburb: 'Bellevue Hill', state: 'NSW', region_id: 1 },
  { postcode: '2025', suburb: 'Woollahra', state: 'NSW', region_id: 1 },
  { postcode: '2027', suburb: 'Darling Point', state: 'NSW', region_id: 1 },
  { postcode: '2011', suburb: 'Potts Point', state: 'NSW', region_id: 1 },
  { postcode: '2044', suburb: 'St Peters', state: 'NSW', region_id: 1 },
  { postcode: '2204', suburb: 'Marrickville', state: 'NSW', region_id: 1 },
  { postcode: '2040', suburb: 'Leichhardt', state: 'NSW', region_id: 1 },
  { postcode: '2041', suburb: 'Balmain', state: 'NSW', region_id: 1 },
  { postcode: '2039', suburb: 'Rozelle', state: 'NSW', region_id: 1 },
  { postcode: '2037', suburb: 'Glebe', state: 'NSW', region_id: 1 },
  { postcode: '2007', suburb: 'Ultimo', state: 'NSW', region_id: 1 },
  { postcode: '2009', suburb: 'Pyrmont', state: 'NSW', region_id: 1 },
  { postcode: '2122', suburb: 'Eastwood', state: 'NSW', region_id: 1 },
  { postcode: '2116', suburb: 'Rydalmere', state: 'NSW', region_id: 1 },
  { postcode: '2117', suburb: 'Dundas', state: 'NSW', region_id: 1 },
  { postcode: '2142', suburb: 'Granville', state: 'NSW', region_id: 1 },
  { postcode: '2160', suburb: 'Merrylands', state: 'NSW', region_id: 1 },
  { postcode: '2161', suburb: 'Guildford', state: 'NSW', region_id: 1 },
  { postcode: '2164', suburb: 'Wetherill Park', state: 'NSW', region_id: 1 },
  { postcode: '2750', suburb: 'Penrith', state: 'NSW', region_id: 1 },
  { postcode: '2756', suburb: 'Windsor', state: 'NSW', region_id: 1 },
];

const melbourneSuburbs = [
  { postcode: '3000', suburb: 'Melbourne', state: 'VIC', region_id: 2 },
  { postcode: '3141', suburb: 'South Yarra', state: 'VIC', region_id: 2 },
  { postcode: '3142', suburb: 'Toorak', state: 'VIC', region_id: 2 },
  { postcode: '3181', suburb: 'Prahran', state: 'VIC', region_id: 2 },
  { postcode: '3066', suburb: 'Collingwood', state: 'VIC', region_id: 2 },
  { postcode: '3067', suburb: 'Abbotsford', state: 'VIC', region_id: 2 },
  { postcode: '3121', suburb: 'Richmond', state: 'VIC', region_id: 2 },
  { postcode: '3065', suburb: 'Fitzroy', state: 'VIC', region_id: 2 },
  { postcode: '3122', suburb: 'Hawthorn', state: 'VIC', region_id: 2 },
  { postcode: '3124', suburb: 'Camberwell', state: 'VIC', region_id: 2 },
  { postcode: '3128', suburb: 'Box Hill', state: 'VIC', region_id: 2 },
  { postcode: '3103', suburb: 'Balwyn', state: 'VIC', region_id: 2 },
  { postcode: '3104', suburb: 'Balwyn North', state: 'VIC', region_id: 2 },
  { postcode: '3126', suburb: 'Canterbury', state: 'VIC', region_id: 2 },
  { postcode: '3127', suburb: 'Surrey Hills', state: 'VIC', region_id: 2 },
  { postcode: '3150', suburb: 'Glen Waverley', state: 'VIC', region_id: 2 },
  { postcode: '3170', suburb: 'Mulgrave', state: 'VIC', region_id: 2 },
  { postcode: '3168', suburb: 'Clayton', state: 'VIC', region_id: 2 },
  { postcode: '3204', suburb: 'Bentleigh', state: 'VIC', region_id: 2 },
  { postcode: '3186', suburb: 'Brighton', state: 'VIC', region_id: 2 },
  { postcode: '3191', suburb: 'Sandringham', state: 'VIC', region_id: 2 },
  { postcode: '3193', suburb: 'Beaumaris', state: 'VIC', region_id: 2 },
  { postcode: '3194', suburb: 'Mentone', state: 'VIC', region_id: 2 },
  { postcode: '3192', suburb: 'Cheltenham', state: 'VIC', region_id: 2 },
  { postcode: '3189', suburb: 'Moorabbin', state: 'VIC', region_id: 2 },
  { postcode: '3162', suburb: 'Caulfield', state: 'VIC', region_id: 2 },
  { postcode: '3185', suburb: 'Elsternwick', state: 'VIC', region_id: 2 },
  { postcode: '3184', suburb: 'Elwood', state: 'VIC', region_id: 2 },
  { postcode: '3182', suburb: 'St Kilda', state: 'VIC', region_id: 2 },
  { postcode: '3183', suburb: 'St Kilda East', state: 'VIC', region_id: 2 },
  { postcode: '3004', suburb: 'St Kilda Road', state: 'VIC', region_id: 2 },
  { postcode: '3008', suburb: 'Docklands', state: 'VIC', region_id: 2 },
  { postcode: '3006', suburb: 'Southbank', state: 'VIC', region_id: 2 },
  { postcode: '3052', suburb: 'Parkville', state: 'VIC', region_id: 2 },
  { postcode: '3053', suburb: 'Carlton', state: 'VIC', region_id: 2 },
  { postcode: '3054', suburb: 'Carlton North', state: 'VIC', region_id: 2 },
  { postcode: '3068', suburb: 'Fitzroy North', state: 'VIC', region_id: 2 },
  { postcode: '3070', suburb: 'Northcote', state: 'VIC', region_id: 2 },
  { postcode: '3071', suburb: 'Thornbury', state: 'VIC', region_id: 2 },
  { postcode: '3072', suburb: 'Preston', state: 'VIC', region_id: 2 },
  { postcode: '3073', suburb: 'Reservoir', state: 'VIC', region_id: 2 },
  { postcode: '3058', suburb: 'Coburg', state: 'VIC', region_id: 2 },
  { postcode: '3056', suburb: 'Brunswick', state: 'VIC', region_id: 2 },
  { postcode: '3011', suburb: 'Footscray', state: 'VIC', region_id: 2 },
  { postcode: '3012', suburb: 'West Footscray', state: 'VIC', region_id: 2 },
  { postcode: '3013', suburb: 'Yarraville', state: 'VIC', region_id: 2 },
  { postcode: '3040', suburb: 'Essendon', state: 'VIC', region_id: 2 },
  { postcode: '3039', suburb: 'Moonee Ponds', state: 'VIC', region_id: 2 },
  { postcode: '3033', suburb: 'Keilor East', state: 'VIC', region_id: 2 },
  { postcode: '3042', suburb: 'Keilor Park', state: 'VIC', region_id: 2 },
  { postcode: '3041', suburb: 'Strathmore', state: 'VIC', region_id: 2 },
  { postcode: '3043', suburb: 'Tullamarine', state: 'VIC', region_id: 2 },
  { postcode: '3088', suburb: 'Greensborough', state: 'VIC', region_id: 2 },
  { postcode: '3089', suburb: 'Diamond Creek', state: 'VIC', region_id: 2 },
  { postcode: '3095', suburb: 'Eltham', state: 'VIC', region_id: 2 },
  { postcode: '3140', suburb: 'Lilydale', state: 'VIC', region_id: 2 },
  { postcode: '3160', suburb: 'Belgrave', state: 'VIC', region_id: 2 },
  { postcode: '3156', suburb: 'Ferntree Gully', state: 'VIC', region_id: 2 },
  { postcode: '3153', suburb: 'Bayswater', state: 'VIC', region_id: 2 },
  { postcode: '3155', suburb: 'Boronia', state: 'VIC', region_id: 2 },
  { postcode: '3179', suburb: 'Scoresby', state: 'VIC', region_id: 2 },
  { postcode: '3178', suburb: 'Rowville', state: 'VIC', region_id: 2 },
  { postcode: '3180', suburb: 'Knoxfield', state: 'VIC', region_id: 2 },
  { postcode: '3175', suburb: 'Dandenong', state: 'VIC', region_id: 2 },
  { postcode: '3171', suburb: 'Springvale', state: 'VIC', region_id: 2 },
  { postcode: '3174', suburb: 'Noble Park', state: 'VIC', region_id: 2 },
  { postcode: '3173', suburb: 'Keysborough', state: 'VIC', region_id: 2 },
  { postcode: '3136', suburb: 'Croydon', state: 'VIC', region_id: 2 },
  { postcode: '3134', suburb: 'Ringwood', state: 'VIC', region_id: 2 },
  { postcode: '3135', suburb: 'Heathmont', state: 'VIC', region_id: 2 },
  { postcode: '3106', suburb: 'Templestowe', state: 'VIC', region_id: 2 },
  { postcode: '3107', suburb: 'Templestowe Lower', state: 'VIC', region_id: 2 },
  { postcode: '3105', suburb: 'Bulleen', state: 'VIC', region_id: 2 },
  { postcode: '3079', suburb: 'Ivanhoe', state: 'VIC', region_id: 2 },
  { postcode: '3084', suburb: 'Heidelberg', state: 'VIC', region_id: 2 },
  { postcode: '3081', suburb: 'Heidelberg West', state: 'VIC', region_id: 2 },
  { postcode: '3078', suburb: 'Fairfield', state: 'VIC', region_id: 2 },
  { postcode: '3220', suburb: 'Geelong', state: 'VIC', region_id: 2 },
  { postcode: '3030', suburb: 'Werribee', state: 'VIC', region_id: 2 },
  { postcode: '3020', suburb: 'Sunshine', state: 'VIC', region_id: 2 },
];

module.exports = {
  sydneySuburbs,
  melbourneSuburbs,
  allSuburbs: [...sydneySuburbs, ...melbourneSuburbs],
};
